version: '3.9'
services:
  #  webserver:
  #    image: 'nginx:alpine'
  #    container_name: pa-portal-backend-webserver
  #    volumes:
  #      - './:/var/www'
  #      - './.docker/nginx/conf.d/:/etc/nginx/conf.d/'
  #    environment:
  #      PORTAL_ENVIRONMENT: development
  #
  #    networks:
  #      - internal
  #      - web
  app:
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    container_name: pa-portal-backend-app
    working_dir: /var/www
    volumes:
      - './:/var/www'
    environment:
      PORTAL_ENVIRONMENT: development
    labels:
      - traefik.enable=true
      - traefik.http.services.pa-portal-backend-app.loadbalancer.server.port=9000
      - traefik.http.routers.pa-portal-backend-app.service=pa-portal-backend-app
      - traefik.http.routers.pa-portal-backend-app.rule=Host(`portal.backend.docker.localhost`)
      - traefik.http.routers.pa-portal-backend-app.entrypoints=https
      - traefik.http.routers.pa-portal-backend-app.tls=true
    networks:
      - internal
      - web

  cli:
    build:
      context: .
      dockerfile: ./.docker/php-cli/Dockerfile
    working_dir: /var/www
    container_name: pa-portal-backend--cli
    volumes:
      - './:/var/www'
    labels:
      - traefik.enable=false
    environment:
      PORTAL_ENVIRONMENT: development
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: pa-portal-redis
    labels:
      - traefik.enable=false
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    external: false