version: '3.7'
services:
    webserver:
        image: 'nginx:alpine'
        volumes:
            - './:/var/www'
            - './.docker/nginx/conf.d/:/etc/nginx/conf.d/'
        environment:
            PORTAL_ENVIRONMENT: development
        ports:
            - '100:80'
        networks:
            - pa-portal-network

    app:
        build:
            context: .
            dockerfile: ./.docker/php-fpm/Dockerfile
        working_dir: /var/www
        volumes:
            - './:/var/www'
        environment:
            PORTAL_ENVIRONMENT: development
        networks:
            - pa-portal-network

    mysql:
        platform: linux/x86_64
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'pa-portal'
            MYSQL_USER: 'pa-portal-user'
            MYSQL_PASSOWRD: 'pa-portal-password'
            MYSQL_ROOT_PASSWORD: 'pa-portal-root-password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - pa-portal-database
        networks:
            - pa-portal-network

    redis:
        image: redis:latest
        container_name: pa-portal-redis
        networks:
            - pa-portal-network

networks:
    pa-portal-network:
        driver: bridge

volumes:
    pa-portal-database: