version: '3.7'
services:
    app:
        image: webdevops/php-nginx-dev:8.0-alpine
        container_name: pa-portal-app
        restart: unless-stopped
        ports:
            - "8082:80"
        volumes:
            - ./:/var/www
        environment:
            PORTAL_ENVIRONMENT: develoment
        networks:
            - pa-portal-network

    redis:
        image: redis:latest
        container_name: pa-portal-redis
        networks:
            - pa-portal-network

networks:
    pa-portal-network:
        driver: bridge