version: '3.9'
services:
  webserver:
    image: 'nginx:alpine'
    container_name: pa-portal-backend-webserver
    volumes:
      - './:/var/www'
      - './.docker/nginx/conf.d:/etc/nginx/conf.d'
    environment:
      PORTAL_ENVIRONMENT: development
    labels:
      - traefik.enable=true
      - traefik.http.services.pa-portal-backend-webserver.loadbalancer.server.port=80
      - traefik.http.routers.pa-portal-backend-webserver.service=pa-portal-backend-webserver
      - traefik.http.routers.pa-portal-backend-webserver.rule=Host(`portal.backend.docker.localhost`)
      - traefik.http.routers.pa-portal-backend-webserver.entrypoints=web
    networks:
      - internal
      - web

  app:
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    container_name: pa-portal-backend-app
    working_dir: /var/www
    volumes:
      - '.:/var/www'
    environment:
      PORTAL_ENVIRONMENT: development
    labels:
      - traefik.enable=false
    networks:
      - internal
      - web

  redis:
    image: redis:latest
    container_name: pa-portal-redis
    labels:
      - traefik.enable=false
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    external: false