version: '3.9'
services:
  webserver:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - './:/var/www'
      - './.docker/nginx/conf.d/:/etc/nginx/conf.d/'
    labels:
      - traefik.enable=true
      - traefik.http.services.pa-portal-backend-webserver.loadbalancer.server.port=80
      - traefik.http.routers.pa-portal-backend-webserver.service=pa-portal-backend-webserver
      - traefik.http.routers.pa-portal-backend-webserver.rule=Host(`portal-backend.docker.localhost`)
      - traefik.http.routers.pa-portal-backend-webserver.entrypoints=https
      - traefik.http.routers.pa-portal-backend-webserver.tls=true
    networks:
      - pa-portal

  app:
    build:
      context: .
      dockerfile: .docker/php-fpm/dev/Dockerfile
    working_dir: /var/www
    volumes:
      - './:/var/www'
    environment:
      PORTAL_ENVIRONMENT: development
    labels:
      - traefik.enable=false
    networks:
      - pa-portal

  cli:
    build:
      context: .
      dockerfile: ./.docker/php-cli/Dockerfile
    working_dir: /var/www
    volumes:
      - './:/var/www'
    labels:
      - traefik.enable=false
    environment:
      PORTAL_ENVIRONMENT: development
    networks:
      - pa-portal

  redis:
    image: redis:latest
    container_name: pa-portal-redis
    labels:
      - traefik.enable=false
    networks:
      - pa-portal

networks:
  pa-portal:
    external: true
