POST {{ baseUrl}}/api/update/project
Content-Type: multipart/form-data; boundary=boundary
Accept: */*
Authorization: Bearer {{ bearerToken }}

--boundary
Content-Disposition: form-data; name="file"; filename="generiot.jsond"

< Dynamic%20SALSA%20-%20SMART.json