#GET {{ baseUrl }}/api/list/partner?filter=&page=1&pageSize=30&sort=latestVersionCosts&order=asc
#GET {{ baseUrl }}/api/list/partner?filter=&query=&order=&direction=asc&page=1&pageSize=1000&organisation=em-engineering-methods-ag
GET {{ baseUrl }}/api/list/partner?filter=&query=&order=&direction=asc&page=1&pageSize=1000&project=cypress
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ bearerToken }}