GET https://dev1.itea4.org/api/statistics/facets?output=1&filter=eyJjb3VudHJ5IjpbXSwiY291bnRyeV9tZXRob2QiOiJvciIsInBhcnRuZXJfdHlwZSI6W10sInBhcnRuZXJfdHlwZV9tZXRob2QiOiJvciIsInByb2plY3Rfc3RhdHVzIjpbXSwicHJvamVjdF9zdGF0dXNfbWV0aG9kIjoib3IiLCJwcmltYXJ5X2NsdXN0ZXJfc3RhdHVzIjpbXSwicHJpbWFyeV9jbHVzdGVyX21ldGhvZCI6Im9yIn0==
Accept: application/json
Content-Type: application/json
#Authorization: Bearer 48c103d1ab7d66b1baf35d8b2b726e2c9effc63c #johan
Authorization: Bearer b0d221286954c2ce35c4c14db60d47713e8eecd0 #holger [GER]
