<div class="container">
    <h1>Authorize</h1>

    <form method="post">
        <label>Do You Authorize</label><br/>
        <small class="text-muted">{{ clientId }}</small>
        <br>
        <br>
        <button class="btn btn-primary" type="submit" name="authorized" value="yes">Yes</button>
        <button class="btn btn-secondary" type="submit" name="authorized" value="no">No</button>
    </form>
</div>
