<?php
return [
    'admin/role/view' => __DIR__ . '/./view/admin/role/view.twig',
    'admin/role/edit' => __DIR__ . '/./view/admin/role/edit.twig',
    'admin/role/new' => __DIR__ . '/./view/admin/role/new.twig',
    'admin/role/list' => __DIR__ . '/./view/admin/role/list.twig',
    'admin/o-auth2/scope/view' => __DIR__ . '/./view/admin/o-auth2/scope/view.twig',
    'admin/o-auth2/scope/edit' => __DIR__ . '/./view/admin/o-auth2/scope/edit.twig',
    'admin/o-auth2/scope/new' => __DIR__ . '/./view/admin/o-auth2/scope/new.twig',
    'admin/o-auth2/scope/list' => __DIR__ . '/./view/admin/o-auth2/scope/list.twig',
    'admin/o-auth2/service/view' => __DIR__ . '/./view/admin/o-auth2/service/view.twig',
    'admin/o-auth2/service/edit' => __DIR__ . '/./view/admin/o-auth2/service/edit.twig',
    'admin/o-auth2/service/new' => __DIR__ . '/./view/admin/o-auth2/service/new.twig',
    'admin/o-auth2/service/list' => __DIR__ . '/./view/admin/o-auth2/service/list.twig',
    'admin/o-auth2/client/view' => __DIR__ . '/./view/admin/o-auth2/client/view.twig',
    'admin/o-auth2/client/edit' => __DIR__ . '/./view/admin/o-auth2/client/edit.twig',
    'admin/o-auth2/client/new' => __DIR__ . '/./view/admin/o-auth2/client/new.twig',
    'admin/o-auth2/client/list' => __DIR__ . '/./view/admin/o-auth2/client/list.twig',
    'admin/cache/index' => __DIR__ . '/./view/admin/cache/index.twig',
    'admin/partial/form/oauth2/scope' => __DIR__ . '/./view/admin/partial/form/oauth2/scope.twig',
    'admin/partial/form/oauth2/service' => __DIR__ . '/./view/admin/partial/form/oauth2/service.twig',
    'admin/partial/form/oauth2/client' => __DIR__ . '/./view/admin/partial/form/oauth2/client.twig',
    'admin/user/view' => __DIR__ . '/./view/admin/user/view.twig',
    'admin/user/change-password' => __DIR__ . '/./view/admin/user/change-password.twig',
    'admin/user/lost-password' => __DIR__ . '/./view/admin/user/lost-password.twig',
    'admin/user/login' => __DIR__ . '/./view/admin/user/login.twig',
    'admin/user/list' => __DIR__ . '/./view/admin/user/list.twig',
];