<?php
/**
 * ITEA Office all rights reserved
 *
 * @author      Johan van der Heide <johan.van.der.heide@itea3.org>
 * @copyright   Copyright (c) 2021 ITEA Office (https://itea3.org)
 * @license     https://itea3.org/license.txt proprietary
 */

// Generated by Laminas ./bin/templatemap_generator.php
return array(
    'admin/user/view'              => __DIR__ . '/view/admin/user/view.twig',
    'admin/user/list'              => __DIR__ . '/view/admin/user/list.twig',
    'admin/user/profile'           => __DIR__ . '/view/admin/user/profile.twig',
    'admin/user/edit'              => __DIR__ . '/view/admin/user/edit.twig',
    'admin/permit/edit-role'       => __DIR__ . '/view/admin/permit/edit-role.twig',
    'admin/permit/new-role'        => __DIR__ . '/view/admin/permit/new-role.twig',
    'admin/permit/new-setter'      => __DIR__ . '/view/admin/permit/new-setter.twig',
    'admin/permit/view-entity'     => __DIR__ . '/view/admin/permit/view-entity.twig',
    'admin/permit/new-entity'      => __DIR__ . '/view/admin/permit/new-entity.twig',
    'admin/permit/list-entity'     => __DIR__ . '/view/admin/permit/list-entity.twig',
    'admin/permit/edit-setter'     => __DIR__ . '/view/admin/permit/edit-setter.twig',
    'admin/permit/edit-entity'     => __DIR__ . '/view/admin/permit/edit-entity.twig',
    'admin/permit/flush'           => __DIR__ . '/view/admin/permit/flush.twig',
    'admin/log/view'               => __DIR__ . '/view/admin/log/view.twig',
    'admin/log/list'               => __DIR__ . '/view/admin/log/list.twig',
    'admin/template/view'          => __DIR__ . '/view/admin/template/view.twig',
    'admin/template/new'           => __DIR__ . '/view/admin/template/new.twig',
    'admin/template/list'          => __DIR__ . '/view/admin/template/list.twig',
    'admin/template/edit'          => __DIR__ . '/view/admin/template/edit.twig',
    'admin/user-admin/view'        => __DIR__ . '/view/admin/user-admin/view.twig',
    'admin/user-admin/new'         => __DIR__ . '/view/admin/user-admin/new.twig',
    'admin/user-admin/impersonate' => __DIR__ . '/view/admin/user-admin/impersonate.twig',
    'admin/user-admin/list'        => __DIR__ . '/view/admin/user-admin/list.twig',
    'admin/user-admin/edit'        => __DIR__ . '/view/admin/user-admin/edit.twig',
    'admin/index/index'            => __DIR__ . '/view/admin/index/index.twig',
    'admin/role/view'              => __DIR__ . '/view/admin/role/view.twig',
    'admin/role/new'               => __DIR__ . '/view/admin/role/new.twig',
    'admin/role/list'              => __DIR__ . '/view/admin/role/list.twig',
    'admin/role/edit'              => __DIR__ . '/view/admin/role/edit.twig',
    'admin/selection/view'         => __DIR__ . '/view/admin/selection/view.twig',
    'admin/selection/new'          => __DIR__ . '/view/admin/selection/new.twig',
    'admin/selection/list'         => __DIR__ . '/view/admin/selection/list.twig',
    'admin/selection/edit'         => __DIR__ . '/view/admin/selection/edit.twig',
    'admin/selection/edit-users'   => __DIR__ . '/view/admin/selection/edit-users.twig',
    'admin/api/log/view'           => __DIR__ . '/view/admin/api/log/view.twig',
    'admin/api/log/list'           => __DIR__ . '/view/admin/api/log/list.twig',
    'admin/cache/index'            => __DIR__ . '/view/admin/cache/index.twig',
    'admin/queue/view'             => __DIR__ . '/view/admin/queue/view.twig',
    'admin/queue/list'             => __DIR__ . '/view/admin/queue/list.twig',
    'admin/error/index'            => __DIR__ . '/view/admin/error/index.twig',
    'admin/support/view'           => __DIR__ . '/view/admin/support/view.twig',
    'admin/support/new'            => __DIR__ . '/view/admin/support/new.twig',
    'admin/support/list'           => __DIR__ . '/view/admin/support/list.twig',
    'admin/support/edit'           => __DIR__ . '/view/admin/support/edit.twig',
    'admin/partial/form/template'  => __DIR__ . '/view/admin/partial/form/template.twig',
    'admin/partial/form/user'      => __DIR__ . '/view/admin/partial/form/user.twig',
    'admin/partial/form/selection' => __DIR__ . '/view/admin/partial/form/selection.twig',
);
