<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'oauth/receive-code'    => __DIR__ . '//view/oauth/receive-code.twig',
    'oauth/authorize'       => __DIR__ . '//view/oauth/authorize.twig',
    'layout/flashmessenger' => __DIR__ . '//view/layout/flashmessenger.twig',
    'layout/layout'         => __DIR__ . '//view/layout/layout.twig',
    'error/403'             => __DIR__ . '//view/error/403.twig',
    'error/404'             => __DIR__ . '//view/error/404.twig',
    'error/index'           => __DIR__ . '//view/error/index.twig',
);
