<?php

declare(strict_types=1);

_('txt-oauth-service-name-label');
_('txt-oauth-service-name-placeholder');
_('txt-oauth-service-name-help-block');
_('txt-oauth-service-client-id-label');
_('txt-oauth-service-client-id-placeholder');
_('txt-oauth-service-client-id-help-block');
_('txt-oauth-service-client-secret-label');
_('txt-oauth-service-client-secret-placeholder');
_('txt-oauth-service-client-secret-help-block');
_('txt-oauth-service-redirect-url-label');
_('txt-oauth-service-redirect-url-placeholder');
_('txt-oauth-service-redirect-url-help-block');
_('txt-oauth-service-authorization-url-label');
_('txt-oauth-service-authorization-url-placeholder');
_('txt-oauth-service-authorization-url-help-block');
_('txt-oauth-service-access-token-url-label');
_('txt-oauth-service-access-token-url-placeholder');
_('txt-oauth-service-access-token-url-help-block');
_('txt-oauth-service-profile-url-label');
_('txt-oauth-service-profile-url-placeholder');
_('txt-oauth-service-profile-url-help-block');
_('txt-oauth-service-allowed-clusters-label');
_('txt-oauth-service-allowed-clusters-help-block');
_('txt-oauth-service-scope-label');
_('txt-oauth-service-scope-help-block');
_('txt-oauth-service-client-label');
_('txt-oauth-service-client-help-block');
