<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Eureka Clusters Backend Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(
        [
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/favicon.ico'
        ]
    )
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css')
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img  src="<?= $this->basePath('/assets/img/logo.png') ?>" alt="Eureka Logo" />Eureka Clusters Backend Application
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->content ?>
    <hr>
    <footer>
        <p>&copy; <?= date('Y') ?> Eureka Clusters Backend Application</p>
    </footer>
</div>
<?= $this->inlineScript()
    ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js') ?>
</body>
</html>
