<?php
/**
 * ITEA Office all rights reserved
 *
 * @author      Johan van der Heide <johan.van.der.heide@itea3.org>
 * @copyright   Copyright (c) 2021 ITEA Office (https://itea3.org)
 * @license     https://itea3.org/license.txt proprietary
 */

// Generated by ZF2's ./bin/templatemap_generator.php
return [
    'app/index/index' => __DIR__ . '//view/app/index/index.twig',
];
