<?php

return [
    'mailing/partial/form/mailer' => __DIR__ . '/./view/mailing/partial/form/mailer.twig',
    'mailing/partial/form/sender' => __DIR__ . '/./view/mailing/partial/form/sender.twig',
    'mailing/partial/form/template' => __DIR__ . '/./view/mailing/partial/form/template.twig',
    'mailing/partial/form/transactional' => __DIR__ . '/./view/mailing/partial/form/transactional.twig',
    'mailing/sender/view' => __DIR__ . '/./view/mailing/sender/view.twig',
    'mailing/sender/edit' => __DIR__ . '/./view/mailing/sender/edit.twig',
    'mailing/sender/new' => __DIR__ . '/./view/mailing/sender/new.twig',
    'mailing/sender/list' => __DIR__ . '/./view/mailing/sender/list.twig',
    'mailing/template/view' => __DIR__ . '/./view/mailing/template/view.twig',
    'mailing/template/edit' => __DIR__ . '/./view/mailing/template/edit.twig',
    'mailing/template/new' => __DIR__ . '/./view/mailing/template/new.twig',
    'mailing/template/list' => __DIR__ . '/./view/mailing/template/list.twig',
    'mailing/mailer/view' => __DIR__ . '/./view/mailing/mailer/view.twig',
    'mailing/mailer/edit' => __DIR__ . '/./view/mailing/mailer/edit.twig',
    'mailing/mailer/new' => __DIR__ . '/./view/mailing/mailer/new.twig',
    'mailing/mailer/list' => __DIR__ . '/./view/mailing/mailer/list.twig',
    'mailing/transactional/view' => __DIR__ . '/./view/mailing/transactional/view.twig',
    'mailing/transactional/edit' => __DIR__ . '/./view/mailing/transactional/edit.twig',
    'mailing/transactional/new' => __DIR__ . '/./view/mailing/transactional/new.twig',
    'mailing/transactional/list' => __DIR__ . '/./view/mailing/transactional/list.twig',
    'mailing/email/view' => __DIR__ . '/./view/mailing/email/view.twig',
    'mailing/email/list' => __DIR__ . '/./view/mailing/email/list.twig',
];
