<?php
/**
 * ITEA Office all rights reserved
 *
 * @author      Johan van der Heide <johan.van.der.heide@itea3.org>
 * @copyright   Copyright (c) 2021 ITEA Office (https://itea3.org)
 * @license     https://itea3.org/license.txt proprietary
 */

// Generated by ZF2's ./bin/templatemap_generator.php
return [
    'cluster/cluster/view' => __DIR__ . '//view/cluster/cluster/view.twig',
    'cluster/cluster/new'  => __DIR__ . '//view/cluster/cluster/new.twig',
    'cluster/cluster/list' => __DIR__ . '//view/cluster/cluster/list.twig',
    'cluster/cluster/edit' => __DIR__ . '//view/cluster/cluster/edit.twig',
];
