<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Eureka Clusters Backend</h1>
</div>

<a class="btn btn-primary btn-lg" href="/oauth2/login/via/itea.html">Login via ITEA Office</a>
<a class="btn btn-primary btn-lg" href="/oauth2/login/via/celtic.html">Login via Celtic</a>
<a class="btn btn-primary btn-lg" href="/oauth2/login/via/penta.html">Login via Penta-Euripides</a>