name: Nginx - Deploy to Github

on:
  push:
    branches:
      - main
      - create-pagination
  pull_request:
    branches:
      - main
      - create-pagination

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Nginx Webserver
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./.docker/nginx/Dockerfile
          push: true
          tags: ghcr.io/eureka-clusters/backend/nginx:latest
